src/Presentation/CAWA.MVCUI/Controllers/AdminController.cs
using CAWA.Application.Absractions.Services;
using CAWA.Application.MethodAnswers;
using CAWA.Application.Services;
using CAWA.Application.ViewModels.AdminVM;
using CAWA.Application.ViewModels.ApplicantInformationVM;
using CAWA.MVCUI.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CAWA.MVCUI.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]
    [TypeFilter(typeof(AdminInformationFilter))]
    public class AdminController : Controller
    {
        #region ctor and required instance
        private readonly ICawaUserService _cawaUserService;
        private readonly IApplicantInformationServices _applicantInformationServices;
        private string? _inviterName;

        public AdminController(ICawaUserService cawaUserService, IApplicantInformationServices applicantInformationServices)
        {
            _cawaUserService = cawaUserService;
            _applicantInformationServices = applicantInformationServices;
        }
        #endregion

        #region actions
        public async Task<IActionResult> Index()
        {
            var answer = await _cawaUserService.GetUser(User.Identity.Name);
            var user = (AdminListVM)answer.user;
            return View(user);
        }

        public async Task<IActionResult> DeniedApplicantList()
        {
            await SetInviterName();
            var answer = await _applicantInformationServices.GetApplicantInformationWithInviterFilter(_inviterName);
            List<ApplicantInformationListVM> vm = answer.ApplicantInformations.Where(x => x.ApprovalStatus == Domain.Enums.ApprovalStatus.Denied).Select(x => (ApplicantInformationListVM)x).ToList();
            SetErrosMessages(answer);
            return View(vm);
        }

        public async Task<IActionResult> ApprovedApplicantList()
        {
            await SetInviterName();
            var answer = await _applicantInformationServices.GetApplicantInformationWithInviterFilter(_inviterName);
            List<ApplicantInformationListVM> vm = answer.ApplicantInformations.Where(x => x.ApprovalStatus == Domain.Enums.ApprovalStatus.Approved).Select(x => (ApplicantInformationListVM)x).ToList();
            SetErrosMessages(answer);
            return View(vm);
        }

        public async Task<IActionResult> PendingApplicantList()
        {
            await SetInviterName();
            var answer = await _applicantInformationServices.GetApplicantInformationWithInviterFilter(_inviterName);
            List<ApplicantInformationListVM> vm = answer.ApplicantInformations.Where(x => x.ApprovalStatus == Domain.Enums.ApprovalStatus.Sent).Select(x => (ApplicantInformationListVM)x).ToList();

            answer.Message = answer.Message == "Başarılı" ? null : answer.Message;
            SetErrosMessages(answer);
            return View(vm);
        }

        public async Task<IActionResult> AllApplicantList()
        {
            await SetInviterName();
            var answer = await _applicantInformationServices.GetApplicantInformationWithInviterFilter(_inviterName);
            List<ApplicantInformationListVM> vm = answer.ApplicantInformations.Select(x => (ApplicantInformationListVM)x).ToList();
            SetErrosMessages(answer);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> ReplyToApplicant(ApplicantInformationResponseVM vm)
        {
            ApplicantInformationServiceAnswer answer = new();

            if (!ModelState.IsValid)
            {
                answer.Message = string.Join(". ", ModelState.Values
                                       .SelectMany(v => v.Errors)
                                       .Select(e => e.ErrorMessage));
                SetErrosMessages(answer);
                return RedirectToAction("GetDetail");
            }

            answer = await _applicantInformationServices.UpdateApplicantInformation(vm, _inviterName);

            SetErrosMessages(answer);
            return RedirectToAction("PendingApplicantList");

        }

        public async Task<IActionResult> GetDetail(string Id)
        {
            var result = await _applicantInformationServices.GetApplicantInformation(Id);
            ApplicantInformationListVM vm = (ApplicantInformationListVM)result.ApplicantInformation;
            return View(vm);
        }
        #endregion

        #region Methods
        private async Task SetInviterName()
        {
            var answer = await _cawaUserService.GetUser(User.Identity.Name);
            _inviterName = answer.user.InviterName;
        }
        private void SetErrosMessages(ApplicantInformationServiceAnswer answer)
        {
            List<string> errorMessages = new List<string>();

            if (!string.IsNullOrEmpty(answer.ExceptionMessage))
            {
                var exceptionErrorMessages = answer.ExceptionMessage.Split(". ", StringSplitOptions.RemoveEmptyEntries);
                errorMessages.AddRange(exceptionErrorMessages);
            }

            if (!string.IsNullOrEmpty(answer.Message)) errorMessages.Add(answer.Message);

            ViewBag.ErrorMessages = errorMessages;
        }
        #endregion
    }
}

src/Presentation/CAWA.MVCUI/Controllers/MailController.cs
using CAWA.Application.Absractions.Services;
using CAWA.Application.ViewModels.MailVM;
using CAWA.MVCUI.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CAWA.MVCUI.Controllers
{
    [TypeFilter(typeof(AdminInformationFilter))]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class MailController : Controller
    {
        private readonly IMailService _mailService;
        public MailController(IMailService mailService)
        {
            _mailService = mailService;
        }

        [HttpGet]
        public async Task<IActionResult> SendMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMail(SendMailVM vm)
        {
            if (!ModelState.IsValid) return View(vm);

            try
            {
                await _mailService.SendMailAsync(vm.Email, vm.Subject, vm.Body, vm.IsHtml);
                TempData["MailMessage"] = "Mail gönderildi";
                return View();
            }
            catch (Exception ex)
            {
                TempData["MailMessage"] = ex.Message;
                return View(vm);
            }
        }

        [HttpGet]
        public async Task<IActionResult> SendInvitationMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendInvitationMail(InvitationMailVM vm)
        {
            if (!ModelState.IsValid) return View(vm);

            if (string.IsNullOrEmpty(vm.Subject))
            {
                vm.Subject = "Bilgilendirme";
            }

            return await SendMail((SendMailVM)vm);
        }
    }
}

src/Presentation/CAWA.MVCUI/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="tr" xmlns="http://www.w3.org/1999/html">
<head>
    <link rel="icon" type="image/png" href="~/img/favicon.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="CAWA YÖNETİCİ PANELİ">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CAWA YÖNETİCİ PANELİ</title>

    <meta name="mobile-web-app-capable" content="yes">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">

    <meta name="msapplication-TileImage" content="img/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,500,300,100,700,900' rel='stylesheet'
          type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="~/css/lib/getmdl-select.min.css">
    <link rel="stylesheet" href="~/css/lib/nv.d3.min.css">
    <link rel="stylesheet" href="~/css/application.min.css">
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header is-small-screen">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                CAWA YÖNETİCİ PANELİ
                <div class="mdl-layout-spacer"></div>

                <div class="avatar-dropdown" id="icon">
                    <span>@(ViewBag.Admin?.Name ?? "Misafir")</span>
                    <img src="@((string)ViewBag.Admin?.PhotoPath ?? "/img/SiluetteUser.png")" style="max-height:30px; max-width:30px;">
                </div>

                <ul class="mdl-menu mdl-list mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-shadow--2dp account-dropdown"
                    for="icon">
                    <li class="mdl-list__item mdl-list__item--two-line">
                        <span class="mdl-list__item-primary-content">
                            <span class="material-icons mdl-list__item-avatar">
                                <img src="@((string)ViewBag.Admin?.PhotoPath ?? "/img/SiluetteUser.png")" style="max-height:30px; max-width:30px;">
                            </span>
                            <span>@User.Identity.Name</span>
                            <span class="mdl-list__item-sub-title">@(ViewBag.Admin?.Email ?? "misafir")</span>
                        </span>
                    </li>

                    <li class="list__item--border-top"></li>

                    <a asp-action="Index" asp-controller="Admin">
                    <li class="mdl-menu__item mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                            <i class="material-icons mdl-list__item-icon">account_circle</i>
                            Profilim
                        </span>
                    </li>
                    </a>

                    <a asp-action="Index" asp-controller="Home">
                    <li class="mdl-menu__item mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                            <i class="material-icons mdl-list__item-icon">home</i>
                            Ana Sayfa
                        </span>
                    </li>
                    </a>

                    <li class="list__item--border-top"></li>

                    <a asp-action="LogOut" asp-controller="Account">
                    <li class="mdl-menu__item mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                            <i class="material-icons mdl-list__item-icon text-color--secondary">exit_to_app</i>
                            Çıkış Yap
                        </span>
                    </li>
                    </a>

                </ul>

                <button id="more"
                        class="mdl-button mdl-js-button mdl-button--icon">
                    <i class="material-icons">more_vert</i>
                </button>

                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mdl-shadow--2dp settings-dropdown"
                    for="more">
                    <a asp-action="AllApplicantList" asp-controller="Admin">
                    <li class="mdl-menu__item">
                        Tüm Başvurular
                    </li>
                    </a>
                    <a asp-action="PendingApplicantList" asp-controller="Admin">
                    <li class="mdl-menu__item">
                        Bekleyen
                    </li>
                    </a>
                    <a asp-action="ApprovedApplicantList" asp-controller="Admin">
                    <li class="mdl-menu__item">
                        Onaylanan
                    </li>
                    </a>
                    <a asp-action="DeniedApplicantList" asp-controller="Admin">
                    <li class="mdl-menu__item">
                        Reddedilen
                    </li>
                    </a>
                </ul>
            </div>
        </header>

        <div class="mdl-layout__drawer">
            <header><img src="~/img/baslık.png" style="max-width:60px; max-height:60px;" /> CAWA</header>
            <div class="scroll__wrapper" id="scroll__wrapper">
                <div class="scroller" id="scroller">
                    <div class="scroll__container" id="scroll__container">
                        <nav class="mdl-navigation">
                            <a class="mdl-navigation__link" asp-action="Index" asp-controller="Admin">
                                <i class="material-icons" role="presentation">person</i>
                                Profilim
                            </a>
                            <a class="mdl-navigation__link" asp-action="Index" asp-controller="Home">
                                <i class="material-icons" role="presentation">home</i>
                                Ana Sayfa
                            </a>
                            <div class="sub-navigation">
                                <a class="mdl-navigation__link">
                                    <i class="material-icons">view_comfy</i>
                                    Başvurular
                                    <i class="material-icons">keyboard_arrow_down</i>
                                </a>
                                <div class="mdl-navigation">
                                    <a class="mdl-navigation__link" asp-action="PendingApplicantList" asp-controller="Admin">
                                        Bekleyenler
                                    </a>
                                    <a class="mdl-navigation__link" asp-action="ApprovedApplicantList" asp-controller="Admin">
                                        Onaylananlar
                                    </a>
                                    <a class="mdl-navigation__link" asp-action="DeniedApplicantList" asp-controller="Admin">
                                        Reddedilenler
                                    </a>
                                    <a class="mdl-navigation__link" asp-action="AllApplicantList" asp-controller="Admin">
                                        Hepsi
                                    </a>
                                </div>
                            </div>

                            <div class="sub-navigation">
                                <a class="mdl-navigation__link">
                                    <i class="material-icons">drafts</i>
                                    Email İşlemleri
                                    <i class="material-icons">keyboard_arrow_down</i>
                                </a>
                                <div class="mdl-navigation">
                                    <a class="mdl-navigation__link" asp-action="SendMail" asp-controller="Mail">
                                        Email Gönder
                                    </a>
                                    <a class="mdl-navigation__link" asp-action="SendInvitationMail" asp-controller="Mail">
                                        Davet Gönder
                                    </a>
                                </div>
                            </div>

                            @if (User.IsInRole("SuperAdmin"))
                            {
                                <div class="sub-navigation">
                                    <a class="mdl-navigation__link">
                                        <i class="material-icons">supervisor_account</i>
                                        Yöneticiler
                                        <i class="material-icons">keyboard_arrow_down</i>
                                    </a>
                                    <div class="mdl-navigation">
                                        <a class="mdl-navigation__link" asp-action="CreateAdmin" asp-controller="SuperAdmin">
                                            Yönetici Oluştur
                                        </a>
                                        <a class="mdl-navigation__link" asp-action="AdminList" asp-controller="SuperAdmin">
                                            Yönetici Listesi
                                        </a>
                                    </div>
                                </div>
                            }
                        </nav>
                    </div>
                </div>
                <div class='scroller__bar' id="scroller__bar"></div>
            </div>
        </div>

        <main class="mdl-layout__content">
            @RenderBody()
        </main>

        <footer class="footer">
            <div style="float:right;">
                <p>&copy; <span id="footer-year"></span> CAWA WEB UYGULAMASI. TÜM HAKLARI SAKLIDIR.</p>
            </div>
        </footer>



    </div>
    <script>
        const currentYear = new Date().getFullYear();
        document.getElementById("footer-year").textContent = currentYear;
    </script>
    <script src="~/js/d3.min.js"></script>
    <script src="~/js/getmdl-select.min.js"></script>
    <script src="~/js/material.min.js"></script>
    <script src="~/js/nv.d3.min.js"></script>
    <script src="~/js/layout/layout.min.js"></script>
    <script src="~/js/scroll/scroll.min.js"></script>
    <script src="~/js/widgets/charts/discreteBarChart.min.js"></script>
    <script src="~/js/widgets/charts/linePlusBarChart.min.js"></script>
    <script src="~/js/widgets/charts/stackedBarChart.min.js"></script>
    <script src="~/js/widgets/employer-form/employer-form.min.js"></script>
    <script src="~/js/widgets/line-chart/line-charts-nvd3.min.js"></script>
    <script src="~/js/widgets/map/maps.min.js"></script>
    <script src="~/js/widgets/pie-chart/pie-charts-nvd3.min.js"></script>
    <script src="~/js/widgets/table/table.min.js"></script>
    <script src="~/js/widgets/todo/todo.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script>
        function previewImage(input) {
            var imagePreview = document.getElementById('imagePreview');
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    imagePreview.src = e.target.result;
                    imagePreview.style.display = 'block';
                };
                reader.readAsDataURL(input.files[0]);
            } else {
                imagePreview.src = '#';
                imagePreview.style.display = 'none';
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $('#IsHtml').change(function () {
                var content = $('#mailBody').val();
                if ($(this).is(':checked')) {
                    $('#previewContent').html(content);
                } else {
                    $('#previewContent').text(content);
                }
            });

            $('#mailBody').on('input', function () {
                var content = $('#mailBody').val();
                if ($('#IsHtml').is(':checked')) {
                    $('#previewContent').html(content);
                } else {
                    $('#previewContent').text(content);
                }
            });
        });
    </script>
</body>
</html>

src/Presentation/CAWA.MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <title>CAWA WEB UYGULAMASI</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link href="~/img/favicon.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <link href="~/css/style.css" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          rel="stylesheet" />

</head>

<body>
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><img src="~/img/baslık.png" style="height:100px; width:100px;" />CAWA</h2>
        </a>
    </nav>
    <!-- Navbar End -->
    <!-- Carousel Start -->
    @RenderBody()

    <footer class="text-primary text-center">
        <div class="container">
            <p>&copy; Cawa Web Uygulaması. <i class="fa fa-book me-3"></i> Tüm hakları saklıdır.</p>
        </div>
    </footer>
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>

    @if (ViewBag.ApprovalStatus == CAWA.Domain.Enums.ApprovalStatus.Sent)
    {
        <script>
            $(document).ready(function () {
                // AJAX isteği her saniyede bir gönderilir
                var interval = setInterval(function () {
                    $.ajax({
                        url: '/Home/CheckUserStatus', // İstek atılacak adres
                        type: 'GET',
                        data: { Id: '@ViewBag.Id' }, // İsteğe ek bilgi gönderilebilir
                        success: function (data) {
                            console.log("Başarı")
                            location.reload();
                        },
                        error: function (data) {
                            console.log("hata");
                        }
                    });
                }, 5000); // 1000 milisaniye = 1 saniye
            });
        </script>
    }

    <script>
        // Birinci fotoğraf
        $("#fileInput1").change(function () {
            readURL(this, "#previewImage1");
        });

        // İkinci fotoğraf
        $("#fileInput2").change(function () {
            readURL(this, "#previewImage2");
        });

        function readURL(input, imgId) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(imgId).attr("src", e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
</body>

</html>